name: Run Jest Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Install project dependencies
      - name: Install dependencies
        run: pnpm install

      # Run Jest tests
      - name: Run Jest tests
        run: pnpm test